name: Update README

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          username: yourusername
          token: ${{ secrets.METRICS_TOKEN }}
